### ISSUE TITLE
Automate versioning & releases with semantic‑release

### ISSUE THREAD

**Issue by JossWritesCode** [JossWritesCode/RiffTube#191]
## Background

We want our repository to automatically bump its version, update `package.json` & `CHANGELOG.md`, and draft GitHub Releases based on Conventional Commits. This removes manual version management, keeps CHANGELOGs in sync, and ensures consistent release workflows.

## Tasks

- [ ] **Install semantic‑release dependencies**  
  - `npm install --save-dev semantic-release @semantic-release/git @semantic-release/github @semantic-release/commit-analyzer @semantic-release/release-notes-generator`  
  - (Optional, if publishing to npm) `npm install --save-dev @semantic-release/npm`

- [ ] **Create a `.releaserc.json` file** at project root with:
    ```jsonc
    {
      "branches": ["main"],
      "tagFormat": "v${version}",
      "plugins": [
        "@semantic-release/commit-analyzer",
        ["@semantic-release/release-notes-generator", { "preset": "conventionalcommits" }],
        ["@semantic-release/git", {
          "assets": ["package.json", "CHANGELOG.md"],
          "message": "chore(release): ${nextRelease.version} [skip ci]\n\n${nextRelease.notes}"
        }],
        "@semantic-release/github"
        // (Optional) "@semantic-release/npm"
      ]
    }
    ```

- [ ] **Add GitHub Actions workflow** at `.github/workflows/release.yml`:
    ```yaml
    name: Release

    on:
      push:
        branches: [ main ]

    jobs:
      release:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v3
            with:
              fetch-depth: 0

          - uses: actions/setup-node@v4
            with:
              node-version: 18
              cache: "npm"

          - run: npm ci

          - name: Run semantic-release
            env:
              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              # NPM_TOKEN: ${{ secrets.NPM_TOKEN }}  # if publishing to npm
            run: npx semantic-release
    ```

- [ ] **Add helper script** in `package.json`:
    ```jsonc
    "scripts": {
      // ...
      "release": "semantic-release"
    }
    ```

- [ ] **Configure repo secrets**  
  - Ensure **GITHUB_TOKEN** is available (provided by Actions)  
  - (If publishing to npm) add **NPM_TOKEN** under Settings → Secrets

## Definition of Done

- [ ] A PR is open against `main` implementing all tasks above  
- [ ] `.releaserc.json` exists and follows the prescribed config  
- [ ] `.github/workflows/release.yml` runs successfully on merge to `main`  
- [ ] `package.json` contains the `release` script  
- [ ] Merging a Conventional Commit into `main`:
  1. Automatically updates `package.json` version  
  2. Updates `CHANGELOG.md` with release notes  
  3. Creates a GitHub Release with the correct tag and notes  
- [ ] (Optional) If publishing to npm, a package is published with the correct version  
- [ ] All existing CI checks and workflows continue passing after merge
