### ISSUE TITLE
CI Pipeline: Set up GitHub Actions for Rails + Vite/React

### ISSUE THREAD

**Issue by JossWritesCode** [JossWritesCode/RiffTube#197]
We want every push and PR to run the full test suite automatically, so broken code never lands on `main`.  
This issue tracks adding a **single GitHub Actions workflow** that tests the Rails API **and** the React/Vite frontend.

---

## Why it matters 💡
| Benefit | Detail |
|---------|--------|
| Catch regressions early | Fails the build if any model/controller/frontend test breaks |
| Enforce style / lint | Runs RuboCop / ESLint / Prettier (we already have scripts) |
| Docs & credibility | Build‑status badge in `README.md` shows our repo is healthy |

---

## Step‑by‑Step 🛠

1. **Create workflow directory**  
   ```bash
   mkdir -p .github/workflows
   ```

2. **Add a workflow file** → `.github/workflows/ci.yml`  
   Paste the starter below (tweak Ruby/Node versions if needed):

   ```yaml
   name: CI

   on:
     push:
       branches: [ main ]
     pull_request:
       branches: [ main ]

   jobs:
     backend:
       name: Rails API
       runs-on: ubuntu-latest

       services:
         postgres:
           image: postgres:15
           env:
             POSTGRES_USER: postgres
             POSTGRES_PASSWORD: postgres
           ports: ['5432:5432']
           options: >-
             --health-cmd "pg_isready -U postgres"
             --health-interval 10s
             --health-timeout 5s
             --health-retries 5

       steps:
         - uses: actions/checkout@v4

         - uses: ruby/setup-ruby@v1
           with:
             ruby-version: 3.2

         - uses: actions/cache@v3
           with:
             path: vendor/bundle
             key: \${{ runner.os }}-gems-\${{ hashFiles('**/Gemfile.lock') }}
             restore-keys: \${{ runner.os }}-gems-

         - name: Install gems
           run: |
             gem install bundler
             bundle config set --local path 'vendor/bundle'
             bundle install --jobs 4 --retry 3

         - name: Prepare DB
           env:
             DATABASE_URL: postgres://postgres:postgres@localhost:5432/rifftube_test
           run: bundle exec rails db:create db:schema:load

         - name: Run Rails tests
           run: bundle exec rails test

     frontend:
       name: Front‑end
       runs-on: ubuntu-latest
       needs: backend

       steps:
         - uses: actions/checkout@v4

         - uses: actions/setup-node@v4
           with:
             node-version: 20

         - uses: actions/cache@v3
           with:
             path: ~/.npm
             key: \${{ runner.os }}-npm-\${{ hashFiles('**/package-lock.json') }}
             restore-keys: \${{ runner.os }}-npm-

         - name: Install packages
           run: npm ci
           working-directory: frontend

         - name: Lint & format
           run: |
             npm run lint
             npm run check-format
           working-directory: frontend

         - name: Run front‑end tests
           run: npm test
           working-directory: frontend
   ```

3. **Commit & push**  
   ```bash
   git add .github/workflows/ci.yml
   git commit -m "chore: add GitHub Actions workflow"
   git push origin main
   ```

4. **Watch the first build**  
   - Go to the **Actions** tab → ensure both “Rails API” and “Front‑end” jobs go green.  
   - Fix any failing tests/lint errors until green.

5. **Add a badge to `README.md`** (optional but nice):  
   ```markdown
   ![CI](https://github.com/<owner>/<repo>/actions/workflows/ci.yml/badge.svg)
   ```

6. **(Optional) store secrets**  
   - If your tests need API keys, add them under **Settings ▸ Secrets & variables ▸ Actions** and reference as `\${{ secrets.MY_KEY }}` in the YAML.

---

## ✅ Definition of Done

- [ ] `.github/workflows/ci.yml` committed to repo  
- [ ] Workflow installs Ruby gems & Node packages, boots Postgres service  
- [ ] `bundle exec rails test` passes in CI  
- [ ] `npm run lint && npm test` pass in CI  
- [ ] First build on `main` shows **green** in GitHub Actions  
- [ ] Status badge added to `README.md`  
- [ ] Team informed: every PR must pass CI before merge
